name: "MacOS"
on:
  workflow_dispatch:

jobs:
    MacOS:
      runs-on: macos-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Start tmate session
          uses: mxschmitt/action-tmate@v3
