name: "Ubuntu"
on:
  workflow_dispatch:


jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3
