on:
  workflow_dispatch:

jobs:
    Windows:
      runs-on: windows-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Start tmate session
          uses: mxschmitt/action-tmate@v3
